enum collecting {
    ADD_FIX = 0,
    ADD_FLOAT,
    ADD_DOUBLE,
    SUB_FIX,
    SUB_FLOAT,
    SUB_DOUBLE,
    MUL_FIX,
    MUL_FLOAT,
    MUL_DOUBLE,
    DIV_FIX,
    DIV_FLOAT,
    DIV_DOUBLE,
    REM_FIX,
    REM_FLOAT,
    REM_DOUBLE,
    CAST_FIX_FLOAT,
    CAST_FIX_DOUBLE,
    CAST_FLOAT_FIX,
    CAST_FLOAT_DOUBLE,
    CAST_DOUBLE_FIX,
    CAST_DOUBLE_FLOAT,
    CAST_FIX_FIX,
    COLLECTION_SIZE
};

const char * coll[] = {"ADD_FIX",
        "ADD_FLOAT",
        "ADD_DOUBLE",
        "SUB_FIX",
        "SUB_FLOAT",
        "SUB_DOUBLE",
        "MUL_FIX",
        "MUL_FLOAT",
        "MUL_DOUBLE",
        "DIV_FIX",
        "DIV_FLOAT",
        "DIV_DOUBLE",
        "REM_FIX",
        "REM_FLOAT",
        "REM_DOUBLE",
        "CAST_FIX_FLOAT",
        "CAST_FIX_DOUBLE",
        "CAST_FLOAT_FIX",
        "CAST_FLOAT_DOUBLE",
        "CAST_DOUBLE_FIX",
        "CAST_DOUBLE_FLOAT",
        "CAST_FIX_FIX", "ERRRRRRRRRRORRRRRRRRRRRR"};

double times[COLLECTION_SIZE];
